services:
  php:
    build: .
    ports:
      - "18080:80"
    environment:
      - DB_URL=pdo-mysql://phpyabs:yabbadabbadoo@db/phpyabs
    volumes:
      - .:/var/www/project
    links:
      - db
  db:
    image: mariadb:latest
    volumes:
      - ./application/data/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=phpyabs

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "18090:80"
    links:
      - db:db_server
    depends_on:
      - db
