services:
  php:
    build:
      context: .
    user: "${UID}:${GID}"
    ports:
      - "18080:80"
    environment:
      - DB_URL=pdo-mysql://phpyabs:yabbadabbadoo@db/phpyabs
    volumes:
      - .:/var/www/project
    links:
      - db
  db:
    image: mariadb:latest
    volumes:
      - ./data/sql:/docker-entrypoint-initdb.d
      - ./var/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=phpyabs
    ports:
      - "13306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "18090:80"
    links:
      - db:db_server
    depends_on:
      - db
