services:
  php:
    build:
      context: .
    user: "${UID}:${GID}"
    ports:
      - "18080:80"
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - DATABASE_URL=pdo-mysql://phpyabs:yabbadabbadoo@database/phpyabs
    volumes:
      - .:/var/www/project
    links:
      - database
  database:
    image: mariadb:latest
    volumes:
      - ./data/sql:/docker-entrypoint-initdb.d
      - ./var/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=phpyabs
    ports:
      - "13306:3306"

  node:
    image: node:22-slim
    volumes:
      - .:/app
    working_dir: /app
    command: "npm run dev"
    ports:
      - "5173:5173"

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "18090:80"
    links:
      - database:db
    depends_on:
      - database
