services:
  php:
    build:
      context: .
    user: "${UID}:${GID}"
    ports:
      - "18080:80"
    environment:
      - DATABASE_URL=pdo-mysql://phpyabs:yabbadabbadoo@database/phpyabs
    volumes:
      - .:/var/www/project
    links:
      - database
  database:
    image: mariadb:latest
    volumes:
      - ./data/sql:/docker-entrypoint-initdb.d
      - ./var/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=phpyabs
    ports:
      - "13306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "18090:80"
    links:
      - database:db
    depends_on:
      - database
