version: '3'
services:
  web:
    build: .
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/project
    links:
      - db
  db:
    image: mariadb:latest
    volumes:
      - ./application/data/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=phpyabs
